version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - TZ=America/New_York  # Set your timezone
    volumes:
      - ./public:/usr/share/nginx/html:ro  # For development hot-reload
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3